channels:
  - conda-forge
dependencies:
  - r-base>=4
  - r-data.table=1.14.0
  - r-dplyr=1.0.5
  - r-forcats=0.5.1
  - r-gstat=2.0_7
  - r-irkernel>=1.1
  - r-readr=1.4.0
  - r-purrr=0.3.4
  - r-shiny=1.6.0
  - r-stringr=1.4.0
  - r-tibble
  - r-tidyr=1.1.3
  - r-tidyverse=1.3.0
